import React from "react";
export default function Head()
{
    return(
        <React.Fragment>
            <div>
  title: "Create Next App",
  description: "Generated by create next app",
  </div>

        </React.Fragment>
    )
}
